version: "3.8"

services:
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - /var/lib/mysql
    environment:
      - MYSQL_DATABASE=board
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpassword
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=rootpassword
    links:
      - mysql
    ports:
       - 8080:80
    volumes:
       - /sessions

  python3:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    working_dir: /home/python
    ports:
      - 8000:8000
    volumes:
      - ${SRC_PATH}:/home/python
    tty: true
